import type { Vehicle } from "@/lib/types"

export const vehicles: Vehicle[] = [
  {
    id: "1",
    make: "Toyota",
    model: "Camry",
    year: 2023,
    trim: "XSE V6",
    price: 25000000, // ~25 million Naira
    mileage: 5230,
    exteriorColor: "Midnight Black Metallic",
    interiorColor: "Black",
    drivetrain: "FWD",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.5L V6",
    vin: "4T1BZ1HK1NU123456",
    stockNumber: "TC23001",
    description: "This 2023 Toyota Camry XSE V6 is a rare find in Nigeria with its powerful engine and premium features. Perfect for executives who want comfort and performance.",
    features: [
      "Leather Seats",
      "Navigation System",
      "Panoramic Sunroof",
      "Blind Spot Monitoring",
      "Apple CarPlay & Android Auto",
      "JBL Premium Audio",
      "Adaptive Cruise Control",
      "Lane Departure Warning",
      "360° Camera System",
      "Heated & Ventilated Front Seats",
    ],
    images: [
      "/toyota-camry-1.jpg",
      "/toyota-camry-2.jpg",
      "/toyota-camry-3.jpg",
    ],
    featured: true,
    condition: "Foreign Used",
    bodyType: "Sedan",
    cityMPG: 22,
    highwayMPG: 32,
  },
  {
    id: "2",
    make: "Honda",
    model: "Accord",
    year: 2022,
    trim: "Touring 2.0T",
    price: 18000000, // ~18 million Naira
    mileage: 12750,
    exteriorColor: "Platinum White Pearl",
    interiorColor: "Ivory",
    drivetrain: "FWD",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L Turbo I-4",
    vin: "1HGCV2F98NA123789",
    stockNumber: "HA22015",
    description: "Imported from USA, this Honda Accord comes with full service history and is perfect for Nigerian roads with its comfortable suspension.",
    features: [
      "Leather-Trimmed Seats",
      "Head-Up Display",
      "Wireless Phone Charger",
      "Honda Sensing Safety Suite",
      "Bose Premium Sound System",
      "Heated & Ventilated Front Seats",
      "Heated Rear Seats",
      "Wi-Fi Hotspot Capability",
    ],
    images: [
      "/honda-accord-1.jpg",
      "/honda-accord-2.jpg",
    ],
    featured: false,
    condition: "Foreign Used",
    bodyType: "Sedan",
    cityMPG: 23,
    highwayMPG: 34,
  },
  {
    id: "3",
    make: "Lexus",
    model: "RX 350",
    year: 2021,
    trim: "Luxury",
    price: 32000000, // ~32 million Naira
    mileage: 18500,
    exteriorColor: "Atomic Silver",
    interiorColor: "Black",
    drivetrain: "AWD",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.5L V6",
    vin: "2T2BZMCA5MC123456",
    stockNumber: "LR21008",
    description: "One of the most sought-after SUVs in Nigeria, this Lexus RX 350 comes with all luxury features expected by Nigerian elites.",
    features: [
      "Mark Levinson Sound System",
      "Heads-Up Display",
      "Semi-Aniline Leather Seats",
      "360-Degree Camera",
      "Adaptive Variable Suspension",
      "Panoramic View Monitor",
      "Intelligent Parking Assist",
    ],
    images: [
      "/lexus-rx-1.jpg",
      "/lexus-rx-2.jpg",
      "/lexus-rx-3.jpg",
    ],
    featured: true,
    condition: "Foreign Used",
    bodyType: "SUV",
    cityMPG: 20,
    highwayMPG: 27,
  },
  {
    id: "4",
    make: "Toyota",
    model: "Highlander",
    year: 2020,
    trim: "Limited",
    price: 28000000, // ~28 million Naira
    mileage: 32000,
    exteriorColor: "Ruby Flare Pearl",
    interiorColor: "Black",
    drivetrain: "AWD",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.5L V6",
    vin: "5TDYZ3DC7LS123456",
    stockNumber: "TH20045",
    description: "Perfect family SUV for Nigerian roads with 7-seater capacity and excellent ground clearance. Originally purchased in the US.",
    features: [
      "Leather Seats",
      "12.3-Inch Touchscreen",
      "JBL Premium Audio",
      "Panoramic Moonroof",
      "Heated and Ventilated Front Seats",
      "Bird's Eye View Camera",
      "Dynamic Radar Cruise Control",
    ],
    images: [
      "/toyota-highlander-1.jpg",
      "/toyota-highlander-2.jpg",
    ],
    featured: false,
    condition: "Foreign Used",
    bodyType: "SUV",
    cityMPG: 21,
    highwayMPG: 29,
  },
  {
    id: "5",
    make: "Mercedes-Benz",
    model: "GLE 350",
    year: 2022,
    trim: "4MATIC",
    price: 45000000, // ~45 million Naira
    mileage: 12500,
    exteriorColor: "Obsidian Black",
    interiorColor: "Black",
    drivetrain: "AWD",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L Turbo I-4",
    vin: "4JGDF6EE1NA123456",
    stockNumber: "MG22012",
    description: "UK-used Mercedes GLE 350 with right-hand drive configuration, perfect for Nigerian roads. Comes with comprehensive service history.",
    features: [
      "MB-Tex Upholstery",
      "Ambient Lighting",
      "Active Parking Assist",
      "KEYLESS-GO",
      "Thermotronic Automatic Climate Control",
      "MBUX Multimedia System",
      "Active Distance Assist DISTRONIC",
    ],
    images: [
      "/mercedes-gle-1.jpg",
      "/mercedes-gle-2.jpg",
      "/mercedes-gle-3.jpg",
    ],
    featured: true,
    condition: "Foreign Used",
    bodyType: "SUV",
    cityMPG: 22,
    highwayMPG: 29,
  },
  {
    id: "6",
    make: "Toyota",
    model: "Corolla",
    year: 2022,
    trim: "SE",
    price: 12500000, // ~12.5 million Naira
    mileage: 15000,
    exteriorColor: "Blueprint",
    interiorColor: "Black",
    drivetrain: "FWD",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L I-4",
    vin: "5YFEPMAE6NP123456",
    stockNumber: "TC22035",
    description: "Reliable and fuel-efficient Toyota Corolla, perfect for Nigerian city driving. US import with clean title.",
    features: [
      "Apple CarPlay/Android Auto",
      "Smart Key System",
      "Lane Departure Alert",
      "Automatic Climate Control",
      "Backup Camera",
      "LED Headlights",
    ],
    images: [
      "/toyota-corolla-1.jpg",
      "/toyota-corolla-2.jpg",
    ],
    featured: false,
    condition: "Foreign Used",
    bodyType: "Sedan",
    cityMPG: 31,
    highwayMPG: 40,
  },
  {
    id: "7",
    make: "Land Rover",
    model: "Range Rover Sport",
    year: 2021,
    trim: "HSE Dynamic",
    price: 55000000, // ~55 million Naira
    mileage: 18500,
    exteriorColor: "Fuji White",
    interiorColor: "Ebony",
    drivetrain: "AWD",
    fuelType: "Diesel",
    transmission: "Automatic",
    engine: "3.0L Turbo Diesel V6",
    vin: "SALGS2SV8MA123456",
    stockNumber: "LR21022",
    description: "UK-spec Range Rover Sport with diesel engine - perfect for Nigerian fuel economy and road conditions.",
    features: [
      "Meridian Sound System",
      "Adaptive Dynamics",
      "Terrain Response 2",
      "Head-Up Display",
      "360° Parking Aid",
      "Climate Comfort Seats",
      "Configurable Ambient Lighting",
    ],
    images: [
      "/range-rover-1.jpg",
      "/range-rover-2.jpg",
      "/range-rover-3.jpg",
    ],
    featured: true,
    condition: "Foreign Used",
    bodyType: "SUV",
    cityMPG: 23,
    highwayMPG: 30,
  }
]